import { configDefaults, defineConfig } from "vitest/config";

export default defineConfig({
   test: {
      globals: true,
      coverage: {
         reporter: ["text", "html"],
         exclude: [
            ...configDefaults.exclude,
            "tests/*",
            "dist/*",
            "coverage/*",
            ".prettierrc.mjs",
            "eslint.config.mjs",
            "release.config.mjs",
            "tsdown.config.ts",
            "vitest.config.mjs",
            "src/**/index.ts",
            "src/**/interface_*.ts",
            "src/state/from_state.ts",
            "src/state/join_state.ts",
            "src/state/join_on_state.ts",
            "src/state/select_state.ts",
            "src/state/order_by_state.ts",
            "src/state/where_state.ts",
            "src/state/group_by_state.ts",
            "src/state/having_state.ts",
            "src/state/cte_state.ts",
            "src/state/union_state.ts",
            "src/state/update_state.ts",
            "src/configuration/configuration_delimiters.ts",
         ],
      },
      exclude: [
         ...configDefaults.exclude,
         "dist/*",
         "coverage/*",
         ".prettierrc.mjs",
         "eslint.config.mjs",
         "release.config.mjs",
         "tsdown.config.ts",
         "vitest.config.mjs",
      ],
   },
});
