// GENERATED by tool/gen_views.dart — DO NOT EDIT.
//
// One `abstract interface class` per dialect, redeclaring only the methods that dialect can
// run (present-by-default minus tool/view_manifest.dart's absent set), with builder-returning
// methods rebound to the view and subquery callbacks narrowed to it. `QueryBuilder implements`
// all four. Regenerate with `dart run tool/gen_views.dart`; `--check` fails if this is stale.
part of 'query_builder.dart';

/// The dialect-agnostic tail shared by every view — the members that do not return the builder,
/// so they need no per-dialect narrowing.
abstract interface class SqlBuilderView {
  Dialect get configuration;
  QueryState get state;
  String parseRaw();
  String parse();
  PreparedSql parsePrepared();
}

/// The MssqlQueryBuilder view over the single QueryBuilder runtime class.
abstract interface class MssqlQueryBuilder implements SqlBuilderView {
  MssqlQueryBuilder and();
  MssqlQueryBuilder or();
  MssqlQueryBuilder distinct();
  MssqlQueryBuilder clearAll();
  MssqlQueryBuilder clearFrom();
  MssqlQueryBuilder clearGroupBy();
  MssqlQueryBuilder clearHaving();
  MssqlQueryBuilder clearJoin();
  MssqlQueryBuilder clearLimit();
  MssqlQueryBuilder clearOffset();
  MssqlQueryBuilder clearOrderBy();
  MssqlQueryBuilder clearSelect();
  MssqlQueryBuilder clearDistinct();
  MssqlQueryBuilder clearWhere();
  MssqlQueryBuilder clearCte();
  MssqlQueryBuilder clearUnion();
  MssqlQueryBuilder clearInsert();
  MssqlQueryBuilder clearUpdate();
  MssqlQueryBuilder clearDelete();
  MssqlQueryBuilder clearTop();
  MssqlQueryBuilder selectAll();
  MssqlQueryBuilder selectColumn(String table, String column, {String? alias});
  MssqlQueryBuilder selectColumns(List<ColumnRef> columns);
  MssqlQueryBuilder selectRaw(String rawSelect);
  MssqlQueryBuilder selectRaws(List<String> rawSelects);
  MssqlQueryBuilder selectWithBuilder(
    String alias,
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder selectWindow(
    String fn,
    void Function(WindowBuilder builder) over, {
    String? alias,
  });
  MssqlQueryBuilder selectJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode, {
    String? alias,
  });
  MssqlQueryBuilder selectAggregate(
    AggregateFunction aggregate,
    String table,
    String column, {
    String? alias,
    bool distinct = false,
  });
  MssqlQueryBuilder fromTable(String table, {String? alias, String? owner});
  MssqlQueryBuilder fromTables(List<TableRef> tables);
  MssqlQueryBuilder fromRaw(String rawFrom);
  MssqlQueryBuilder fromRaws(List<String> rawFroms);
  MssqlQueryBuilder fromWithBuilder(
    String alias,
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder fromTableFunction(
    String functionName,
    String alias, [
    List<Object?> params = const [],
  ]);
  MssqlQueryBuilder fromTableFunctionWithOwner(
    String owner,
    String functionName,
    String alias, [
    List<Object?> params = const [],
  ]);
  MssqlQueryBuilder fromFunctionRaw(String rawFrom, String alias);
  MssqlQueryBuilder joinTable(
    JoinType joinType,
    String table,
    void Function(JoinOnBuilder builder) on, {
    String? alias,
    String? owner,
  });
  MssqlQueryBuilder joinTables(List<JoinRef> joins);
  MssqlQueryBuilder joinWithBuilder(
    JoinType joinType,
    String alias,
    void Function(MssqlQueryBuilder builder) builder,
    void Function(JoinOnBuilder builder) on,
  );
  MssqlQueryBuilder joinRaw(String rawJoin);
  MssqlQueryBuilder joinRaws(List<String> rawJoins);
  MssqlQueryBuilder joinCrossApply(
    String alias,
    void Function(MssqlQueryBuilder builder) builder, [
    void Function(JoinOnBuilder builder)? on,
  ]);
  MssqlQueryBuilder joinOuterApply(
    String alias,
    void Function(MssqlQueryBuilder builder) builder, [
    void Function(JoinOnBuilder builder)? on,
  ]);
  MssqlQueryBuilder where(
    String table,
    String column,
    WhereOperator operator,
    Object? value,
  );
  MssqlQueryBuilder whereBetween(
    String table,
    String column,
    Object? from,
    Object? to,
  );
  MssqlQueryBuilder whereRowValue(
    List<GroupByRef> columns,
    WhereOperator operator,
    List<Object?> values,
  );
  MssqlQueryBuilder whereRowValueIn(
    List<GroupByRef> columns,
    List<List<Object?>> tuples,
  );
  MssqlQueryBuilder whereInValues(
    String table,
    String column,
    List<Object?> values,
  );
  MssqlQueryBuilder whereNotInValues(
    String table,
    String column,
    List<Object?> values,
  );
  MssqlQueryBuilder whereNull(String table, String column);
  MssqlQueryBuilder whereNotNull(String table, String column);
  MssqlQueryBuilder whereRaw(String rawWhere);
  MssqlQueryBuilder whereRaws(List<String> rawWheres);
  MssqlQueryBuilder whereJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode,
    WhereOperator operator,
    Object? value,
  );
  MssqlQueryBuilder whereMatch(
    List<MatchColumnRef> columns,
    String query, [
    FullTextMode mode = FullTextMode.natural,
  ]);
  MssqlQueryBuilder whereMatchRaw(String rawWhere);
  MssqlQueryBuilder whereGroup(
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder whereInWithBuilder(
    String table,
    String column,
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder whereNotInWithBuilder(
    String table,
    String column,
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder whereExistsWithBuilder(
    String table,
    String column,
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder whereNotExistsWithBuilder(
    String table,
    String column,
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder whereExists(
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder whereNotExists(
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder groupByColumn(String table, String column);
  MssqlQueryBuilder groupByColumns(List<GroupByRef> columns);
  MssqlQueryBuilder groupByRaw(String rawGroupBy);
  MssqlQueryBuilder groupByRaws(List<String> rawGroupBys);
  MssqlQueryBuilder groupByRollup([List<GroupByRef> columns = const []]);
  MssqlQueryBuilder groupByCube([List<GroupByRef> columns = const []]);
  MssqlQueryBuilder groupByGroupingSets(List<GroupBySetRef> sets);
  MssqlQueryBuilder having(
    String table,
    String column,
    WhereOperator operator,
    Object? value,
  );
  MssqlQueryBuilder havingAggregate(
    AggregateFunction aggregate,
    String table,
    String column,
    WhereOperator operator,
    Object? value, {
    bool distinct = false,
  });
  MssqlQueryBuilder havingRaw(String rawHaving);
  MssqlQueryBuilder havingRaws(List<String> rawHavings);
  MssqlQueryBuilder havingJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode,
    WhereOperator operator,
    Object? value,
  );
  MssqlQueryBuilder havingMatch(
    List<MatchColumnRef> columns,
    String query, [
    FullTextMode mode = FullTextMode.natural,
  ]);
  MssqlQueryBuilder havingBetween(
    String table,
    String column,
    Object? from,
    Object? to,
  );
  MssqlQueryBuilder havingInValues(
    String table,
    String column,
    List<Object?> values,
  );
  MssqlQueryBuilder havingNotInValues(
    String table,
    String column,
    List<Object?> values,
  );
  MssqlQueryBuilder havingNull(String table, String column);
  MssqlQueryBuilder havingNotNull(String table, String column);
  MssqlQueryBuilder havingInWithBuilder(
    String table,
    String column,
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder havingNotInWithBuilder(
    String table,
    String column,
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder havingExists(
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder havingNotExists(
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder havingGroup(
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder orderByColumn(
    String table,
    String column,
    OrderByDirection direction, [
    NullsOrder nulls = NullsOrder.none,
  ]);
  MssqlQueryBuilder orderByColumns(List<OrderByRef> columns);
  MssqlQueryBuilder orderByRaw(String rawOrderBy);
  MssqlQueryBuilder orderByRaws(List<String> rawOrderBys);
  MssqlQueryBuilder limit(int limit);
  MssqlQueryBuilder limitWithTies(int n);
  MssqlQueryBuilder clearLimitWithTies();
  MssqlQueryBuilder offset(int offset);
  MssqlQueryBuilder top(int top);
  MssqlQueryBuilder merge(void Function(MergeBuilder) build);
  MssqlQueryBuilder insertInto(String table, {String? owner});
  MssqlQueryBuilder insertColumns(List<String> columns);
  MssqlQueryBuilder insertValues(List<Object?> values);
  MssqlQueryBuilder insertSelect(
    void Function(MssqlQueryBuilder builder) builder,
  );
  MssqlQueryBuilder insertRaw(String raw);
  MssqlQueryBuilder updateTable(String table, {String? alias, String? owner});
  MssqlQueryBuilder set(String column, Object? value);
  MssqlQueryBuilder setColumns(List<SetRef> columns);
  MssqlQueryBuilder setRaw(String raw);
  MssqlQueryBuilder deleteFrom(String table, {String? alias, String? owner});
  MssqlQueryBuilder union(void Function(MssqlQueryBuilder builder) builder);
  MssqlQueryBuilder unionAll(void Function(MssqlQueryBuilder builder) builder);
  MssqlQueryBuilder intersect(void Function(MssqlQueryBuilder builder) builder);
  MssqlQueryBuilder except(void Function(MssqlQueryBuilder builder) builder);
  MssqlQueryBuilder cte(
    String name,
    void Function(MssqlQueryBuilder builder) builder, [
    List<String> columns = const [],
  ]);
  MssqlQueryBuilder cteRecursive(
    String name,
    void Function(MssqlQueryBuilder builder) builder, [
    List<String> columns = const [],
  ]);
  MssqlQueryBuilder cteRaw(String name, String raw);
  MssqlQueryBuilder returning(List<String> columns);
  MssqlQueryBuilder returningRaw(String raw);
  MssqlQueryBuilder clearReturning();
  MssqlQueryBuilder clearRowLock();
  MssqlQueryBuilder hintMssqlOption(String optionText);
  MssqlQueryBuilder hintRaw(String rawHint);
  MssqlQueryBuilder clearHints();
  MssqlQueryBuilder callProcedure(String name);
  MssqlQueryBuilder callProcedureWithOwner(String owner, String name);
  MssqlQueryBuilder callFunction(
    String name, [
    CallReturnIntent returnIntent = CallReturnIntent.scalar,
  ]);
  MssqlQueryBuilder callFunctionWithOwner(
    String owner,
    String name, [
    CallReturnIntent returnIntent = CallReturnIntent.scalar,
  ]);
  MssqlQueryBuilder procParam(Object? value);
  MssqlQueryBuilder procParams(List<Object?> values);
  MssqlQueryBuilder procParamNamed(String name, Object? value);
  MssqlQueryBuilder procParamRaw(String raw);
  MssqlQueryBuilder procParamOut(String name, [String? sqlType]);
  MssqlQueryBuilder procParamInOut(
    String name,
    Object? value, [
    String? sqlType,
  ]);
  MssqlQueryBuilder clearCall();
  MssqlQueryBuilder updlock();
  MssqlQueryBuilder updlockNowait();
  MssqlQueryBuilder updlockReadpast();
}

/// The MysqlQueryBuilder view over the single QueryBuilder runtime class.
abstract interface class MysqlQueryBuilder implements SqlBuilderView {
  MysqlQueryBuilder and();
  MysqlQueryBuilder or();
  MysqlQueryBuilder distinct();
  MysqlQueryBuilder clearAll();
  MysqlQueryBuilder clearFrom();
  MysqlQueryBuilder clearGroupBy();
  MysqlQueryBuilder clearHaving();
  MysqlQueryBuilder clearJoin();
  MysqlQueryBuilder clearLimit();
  MysqlQueryBuilder clearOffset();
  MysqlQueryBuilder clearOrderBy();
  MysqlQueryBuilder clearSelect();
  MysqlQueryBuilder clearDistinct();
  MysqlQueryBuilder clearWhere();
  MysqlQueryBuilder clearCte();
  MysqlQueryBuilder clearUnion();
  MysqlQueryBuilder clearInsert();
  MysqlQueryBuilder clearUpdate();
  MysqlQueryBuilder clearDelete();
  MysqlQueryBuilder selectAll();
  MysqlQueryBuilder selectColumn(String table, String column, {String? alias});
  MysqlQueryBuilder selectColumns(List<ColumnRef> columns);
  MysqlQueryBuilder selectRaw(String rawSelect);
  MysqlQueryBuilder selectRaws(List<String> rawSelects);
  MysqlQueryBuilder selectWithBuilder(
    String alias,
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder selectWindow(
    String fn,
    void Function(WindowBuilder builder) over, {
    String? alias,
  });
  MysqlQueryBuilder selectJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode, {
    String? alias,
  });
  MysqlQueryBuilder selectAggregate(
    AggregateFunction aggregate,
    String table,
    String column, {
    String? alias,
    bool distinct = false,
  });
  MysqlQueryBuilder fromTable(String table, {String? alias, String? owner});
  MysqlQueryBuilder fromTables(List<TableRef> tables);
  MysqlQueryBuilder fromRaw(String rawFrom);
  MysqlQueryBuilder fromRaws(List<String> rawFroms);
  MysqlQueryBuilder fromWithBuilder(
    String alias,
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder fromLateral(
    String alias,
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder fromFunctionRaw(String rawFrom, String alias);
  MysqlQueryBuilder joinTable(
    JoinType joinType,
    String table,
    void Function(JoinOnBuilder builder) on, {
    String? alias,
    String? owner,
  });
  MysqlQueryBuilder joinTables(List<JoinRef> joins);
  MysqlQueryBuilder joinWithBuilder(
    JoinType joinType,
    String alias,
    void Function(MysqlQueryBuilder builder) builder,
    void Function(JoinOnBuilder builder) on,
  );
  MysqlQueryBuilder joinRaw(String rawJoin);
  MysqlQueryBuilder joinRaws(List<String> rawJoins);
  MysqlQueryBuilder joinLateral(
    String alias,
    void Function(MysqlQueryBuilder builder) builder,
    void Function(JoinOnBuilder builder) on,
  );
  MysqlQueryBuilder where(
    String table,
    String column,
    WhereOperator operator,
    Object? value,
  );
  MysqlQueryBuilder whereBetween(
    String table,
    String column,
    Object? from,
    Object? to,
  );
  MysqlQueryBuilder whereRowValue(
    List<GroupByRef> columns,
    WhereOperator operator,
    List<Object?> values,
  );
  MysqlQueryBuilder whereRowValueIn(
    List<GroupByRef> columns,
    List<List<Object?>> tuples,
  );
  MysqlQueryBuilder whereInValues(
    String table,
    String column,
    List<Object?> values,
  );
  MysqlQueryBuilder whereNotInValues(
    String table,
    String column,
    List<Object?> values,
  );
  MysqlQueryBuilder whereNull(String table, String column);
  MysqlQueryBuilder whereNotNull(String table, String column);
  MysqlQueryBuilder whereRaw(String rawWhere);
  MysqlQueryBuilder whereRaws(List<String> rawWheres);
  MysqlQueryBuilder whereJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode,
    WhereOperator operator,
    Object? value,
  );
  MysqlQueryBuilder whereJsonContains(
    String table,
    String column,
    Object? value,
  );
  MysqlQueryBuilder whereMatch(
    List<MatchColumnRef> columns,
    String query, [
    FullTextMode mode = FullTextMode.natural,
  ]);
  MysqlQueryBuilder whereMatchRaw(String rawWhere);
  MysqlQueryBuilder whereGroup(
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder whereInWithBuilder(
    String table,
    String column,
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder whereNotInWithBuilder(
    String table,
    String column,
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder whereExistsWithBuilder(
    String table,
    String column,
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder whereNotExistsWithBuilder(
    String table,
    String column,
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder whereExists(
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder whereNotExists(
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder groupByColumn(String table, String column);
  MysqlQueryBuilder groupByColumns(List<GroupByRef> columns);
  MysqlQueryBuilder groupByRaw(String rawGroupBy);
  MysqlQueryBuilder groupByRaws(List<String> rawGroupBys);
  MysqlQueryBuilder groupByRollup([List<GroupByRef> columns = const []]);
  MysqlQueryBuilder having(
    String table,
    String column,
    WhereOperator operator,
    Object? value,
  );
  MysqlQueryBuilder havingAggregate(
    AggregateFunction aggregate,
    String table,
    String column,
    WhereOperator operator,
    Object? value, {
    bool distinct = false,
  });
  MysqlQueryBuilder havingRaw(String rawHaving);
  MysqlQueryBuilder havingRaws(List<String> rawHavings);
  MysqlQueryBuilder havingJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode,
    WhereOperator operator,
    Object? value,
  );
  MysqlQueryBuilder havingJsonContains(
    String table,
    String column,
    Object? value,
  );
  MysqlQueryBuilder havingMatch(
    List<MatchColumnRef> columns,
    String query, [
    FullTextMode mode = FullTextMode.natural,
  ]);
  MysqlQueryBuilder havingBetween(
    String table,
    String column,
    Object? from,
    Object? to,
  );
  MysqlQueryBuilder havingInValues(
    String table,
    String column,
    List<Object?> values,
  );
  MysqlQueryBuilder havingNotInValues(
    String table,
    String column,
    List<Object?> values,
  );
  MysqlQueryBuilder havingNull(String table, String column);
  MysqlQueryBuilder havingNotNull(String table, String column);
  MysqlQueryBuilder havingInWithBuilder(
    String table,
    String column,
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder havingNotInWithBuilder(
    String table,
    String column,
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder havingExists(
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder havingNotExists(
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder havingGroup(
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder orderByColumn(
    String table,
    String column,
    OrderByDirection direction, [
    NullsOrder nulls = NullsOrder.none,
  ]);
  MysqlQueryBuilder orderByColumns(List<OrderByRef> columns);
  MysqlQueryBuilder orderByRaw(String rawOrderBy);
  MysqlQueryBuilder orderByRaws(List<String> rawOrderBys);
  MysqlQueryBuilder limit(int limit);
  MysqlQueryBuilder offset(int offset);
  MysqlQueryBuilder insertInto(String table, {String? owner});
  MysqlQueryBuilder insertColumns(List<String> columns);
  MysqlQueryBuilder insertValues(List<Object?> values);
  MysqlQueryBuilder insertSelect(
    void Function(MysqlQueryBuilder builder) builder,
  );
  MysqlQueryBuilder insertRaw(String raw);
  MysqlQueryBuilder updateTable(String table, {String? alias, String? owner});
  MysqlQueryBuilder set(String column, Object? value);
  MysqlQueryBuilder setColumns(List<SetRef> columns);
  MysqlQueryBuilder setRaw(String raw);
  MysqlQueryBuilder deleteFrom(String table, {String? alias, String? owner});
  MysqlQueryBuilder union(void Function(MysqlQueryBuilder builder) builder);
  MysqlQueryBuilder unionAll(void Function(MysqlQueryBuilder builder) builder);
  MysqlQueryBuilder intersect(void Function(MysqlQueryBuilder builder) builder);
  MysqlQueryBuilder except(void Function(MysqlQueryBuilder builder) builder);
  MysqlQueryBuilder cte(
    String name,
    void Function(MysqlQueryBuilder builder) builder, [
    List<String> columns = const [],
  ]);
  MysqlQueryBuilder cteRecursive(
    String name,
    void Function(MysqlQueryBuilder builder) builder, [
    List<String> columns = const [],
  ]);
  MysqlQueryBuilder cteRaw(String name, String raw);
  MysqlQueryBuilder clearUpsert();
  MysqlQueryBuilder forUpdate();
  MysqlQueryBuilder forUpdateNowait();
  MysqlQueryBuilder forUpdateSkipLocked();
  MysqlQueryBuilder forShare();
  MysqlQueryBuilder forShareNowait();
  MysqlQueryBuilder forShareSkipLocked();
  MysqlQueryBuilder clearRowLock();
  MysqlQueryBuilder hintUseIndex(String tableNameOrAlias, String indexName);
  MysqlQueryBuilder hintForceIndex(String tableNameOrAlias, String indexName);
  MysqlQueryBuilder hintRaw(String rawHint);
  MysqlQueryBuilder clearHints();
  MysqlQueryBuilder callProcedure(String name);
  MysqlQueryBuilder callProcedureWithOwner(String owner, String name);
  MysqlQueryBuilder callFunction(
    String name, [
    CallReturnIntent returnIntent = CallReturnIntent.scalar,
  ]);
  MysqlQueryBuilder callFunctionWithOwner(
    String owner,
    String name, [
    CallReturnIntent returnIntent = CallReturnIntent.scalar,
  ]);
  MysqlQueryBuilder procParam(Object? value);
  MysqlQueryBuilder procParams(List<Object?> values);
  MysqlQueryBuilder procParamRaw(String raw);
  MysqlQueryBuilder procParamOut(String name, [String? sqlType]);
  MysqlQueryBuilder procParamInOut(
    String name,
    Object? value, [
    String? sqlType,
  ]);
  MysqlQueryBuilder clearCall();
  MysqlQueryBuilder insertIgnore();
  MysqlQueryBuilder onDuplicateKeyUpdate(List<SetRef> updates);
  MysqlQueryBuilder onDuplicateKeyUpdateRaw(String raw);
  MysqlQueryBuilder joinCrossLateral(
    String alias,
    void Function(MysqlQueryBuilder builder) builder, [
    void Function(JoinOnBuilder builder)? on,
  ]);
  MysqlQueryBuilder joinLeftLateral(
    String alias,
    void Function(MysqlQueryBuilder builder) builder, [
    void Function(JoinOnBuilder builder)? on,
  ]);
}

/// The PostgresQueryBuilder view over the single QueryBuilder runtime class.
abstract interface class PostgresQueryBuilder implements SqlBuilderView {
  PostgresQueryBuilder and();
  PostgresQueryBuilder or();
  PostgresQueryBuilder distinct();
  PostgresQueryBuilder clearAll();
  PostgresQueryBuilder clearFrom();
  PostgresQueryBuilder clearGroupBy();
  PostgresQueryBuilder clearHaving();
  PostgresQueryBuilder clearJoin();
  PostgresQueryBuilder clearLimit();
  PostgresQueryBuilder clearOffset();
  PostgresQueryBuilder clearOrderBy();
  PostgresQueryBuilder clearSelect();
  PostgresQueryBuilder clearDistinct();
  PostgresQueryBuilder distinctOn(List<DistinctOnRef> columns);
  PostgresQueryBuilder clearDistinctOn();
  PostgresQueryBuilder clearWhere();
  PostgresQueryBuilder clearCte();
  PostgresQueryBuilder clearUnion();
  PostgresQueryBuilder clearInsert();
  PostgresQueryBuilder clearUpdate();
  PostgresQueryBuilder clearDelete();
  PostgresQueryBuilder selectAll();
  PostgresQueryBuilder selectColumn(
    String table,
    String column, {
    String? alias,
  });
  PostgresQueryBuilder selectColumns(List<ColumnRef> columns);
  PostgresQueryBuilder selectRaw(String rawSelect);
  PostgresQueryBuilder selectRaws(List<String> rawSelects);
  PostgresQueryBuilder selectWithBuilder(
    String alias,
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder selectWindow(
    String fn,
    void Function(WindowBuilder builder) over, {
    String? alias,
  });
  PostgresQueryBuilder selectJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode, {
    String? alias,
  });
  PostgresQueryBuilder selectAggregate(
    AggregateFunction aggregate,
    String table,
    String column, {
    String? alias,
    bool distinct = false,
  });
  PostgresQueryBuilder fromTable(String table, {String? alias, String? owner});
  PostgresQueryBuilder fromTables(List<TableRef> tables);
  PostgresQueryBuilder fromRaw(String rawFrom);
  PostgresQueryBuilder fromRaws(List<String> rawFroms);
  PostgresQueryBuilder fromWithBuilder(
    String alias,
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder fromLateral(
    String alias,
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder fromTableFunction(
    String functionName,
    String alias, [
    List<Object?> params = const [],
  ]);
  PostgresQueryBuilder fromTableFunctionWithOwner(
    String owner,
    String functionName,
    String alias, [
    List<Object?> params = const [],
  ]);
  PostgresQueryBuilder fromFunctionRaw(String rawFrom, String alias);
  PostgresQueryBuilder joinTable(
    JoinType joinType,
    String table,
    void Function(JoinOnBuilder builder) on, {
    String? alias,
    String? owner,
  });
  PostgresQueryBuilder joinTables(List<JoinRef> joins);
  PostgresQueryBuilder joinWithBuilder(
    JoinType joinType,
    String alias,
    void Function(PostgresQueryBuilder builder) builder,
    void Function(JoinOnBuilder builder) on,
  );
  PostgresQueryBuilder joinRaw(String rawJoin);
  PostgresQueryBuilder joinRaws(List<String> rawJoins);
  PostgresQueryBuilder joinLateral(
    String alias,
    void Function(PostgresQueryBuilder builder) builder,
    void Function(JoinOnBuilder builder) on,
  );
  PostgresQueryBuilder where(
    String table,
    String column,
    WhereOperator operator,
    Object? value,
  );
  PostgresQueryBuilder whereBetween(
    String table,
    String column,
    Object? from,
    Object? to,
  );
  PostgresQueryBuilder whereRowValue(
    List<GroupByRef> columns,
    WhereOperator operator,
    List<Object?> values,
  );
  PostgresQueryBuilder whereRowValueIn(
    List<GroupByRef> columns,
    List<List<Object?>> tuples,
  );
  PostgresQueryBuilder whereInValues(
    String table,
    String column,
    List<Object?> values,
  );
  PostgresQueryBuilder whereNotInValues(
    String table,
    String column,
    List<Object?> values,
  );
  PostgresQueryBuilder whereNull(String table, String column);
  PostgresQueryBuilder whereNotNull(String table, String column);
  PostgresQueryBuilder whereRaw(String rawWhere);
  PostgresQueryBuilder whereRaws(List<String> rawWheres);
  PostgresQueryBuilder whereJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode,
    WhereOperator operator,
    Object? value,
  );
  PostgresQueryBuilder whereJsonContains(
    String table,
    String column,
    Object? value,
  );
  PostgresQueryBuilder whereMatch(
    List<MatchColumnRef> columns,
    String query, [
    FullTextMode mode = FullTextMode.natural,
  ]);
  PostgresQueryBuilder whereMatchRaw(String rawWhere);
  PostgresQueryBuilder whereGroup(
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder whereInWithBuilder(
    String table,
    String column,
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder whereNotInWithBuilder(
    String table,
    String column,
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder whereExistsWithBuilder(
    String table,
    String column,
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder whereNotExistsWithBuilder(
    String table,
    String column,
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder whereExists(
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder whereNotExists(
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder groupByColumn(String table, String column);
  PostgresQueryBuilder groupByColumns(List<GroupByRef> columns);
  PostgresQueryBuilder groupByRaw(String rawGroupBy);
  PostgresQueryBuilder groupByRaws(List<String> rawGroupBys);
  PostgresQueryBuilder groupByRollup([List<GroupByRef> columns = const []]);
  PostgresQueryBuilder groupByCube([List<GroupByRef> columns = const []]);
  PostgresQueryBuilder groupByGroupingSets(List<GroupBySetRef> sets);
  PostgresQueryBuilder having(
    String table,
    String column,
    WhereOperator operator,
    Object? value,
  );
  PostgresQueryBuilder havingAggregate(
    AggregateFunction aggregate,
    String table,
    String column,
    WhereOperator operator,
    Object? value, {
    bool distinct = false,
  });
  PostgresQueryBuilder havingRaw(String rawHaving);
  PostgresQueryBuilder havingRaws(List<String> rawHavings);
  PostgresQueryBuilder havingJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode,
    WhereOperator operator,
    Object? value,
  );
  PostgresQueryBuilder havingJsonContains(
    String table,
    String column,
    Object? value,
  );
  PostgresQueryBuilder havingMatch(
    List<MatchColumnRef> columns,
    String query, [
    FullTextMode mode = FullTextMode.natural,
  ]);
  PostgresQueryBuilder havingBetween(
    String table,
    String column,
    Object? from,
    Object? to,
  );
  PostgresQueryBuilder havingInValues(
    String table,
    String column,
    List<Object?> values,
  );
  PostgresQueryBuilder havingNotInValues(
    String table,
    String column,
    List<Object?> values,
  );
  PostgresQueryBuilder havingNull(String table, String column);
  PostgresQueryBuilder havingNotNull(String table, String column);
  PostgresQueryBuilder havingInWithBuilder(
    String table,
    String column,
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder havingNotInWithBuilder(
    String table,
    String column,
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder havingExists(
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder havingNotExists(
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder havingGroup(
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder orderByColumn(
    String table,
    String column,
    OrderByDirection direction, [
    NullsOrder nulls = NullsOrder.none,
  ]);
  PostgresQueryBuilder orderByColumns(List<OrderByRef> columns);
  PostgresQueryBuilder orderByRaw(String rawOrderBy);
  PostgresQueryBuilder orderByRaws(List<String> rawOrderBys);
  PostgresQueryBuilder limit(int limit);
  PostgresQueryBuilder limitWithTies(int n);
  PostgresQueryBuilder clearLimitWithTies();
  PostgresQueryBuilder offset(int offset);
  PostgresQueryBuilder insertInto(String table, {String? owner});
  PostgresQueryBuilder insertColumns(List<String> columns);
  PostgresQueryBuilder insertValues(List<Object?> values);
  PostgresQueryBuilder insertSelect(
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder insertRaw(String raw);
  PostgresQueryBuilder updateTable(
    String table, {
    String? alias,
    String? owner,
  });
  PostgresQueryBuilder set(String column, Object? value);
  PostgresQueryBuilder setColumns(List<SetRef> columns);
  PostgresQueryBuilder setRaw(String raw);
  PostgresQueryBuilder deleteFrom(String table, {String? alias, String? owner});
  PostgresQueryBuilder union(
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder unionAll(
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder intersect(
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder except(
    void Function(PostgresQueryBuilder builder) builder,
  );
  PostgresQueryBuilder cte(
    String name,
    void Function(PostgresQueryBuilder builder) builder, [
    List<String> columns = const [],
  ]);
  PostgresQueryBuilder cteRecursive(
    String name,
    void Function(PostgresQueryBuilder builder) builder, [
    List<String> columns = const [],
  ]);
  PostgresQueryBuilder cteRaw(String name, String raw);
  PostgresQueryBuilder returning(List<String> columns);
  PostgresQueryBuilder returningRaw(String raw);
  PostgresQueryBuilder clearReturning();
  PostgresQueryBuilder onConflictDoNothing([
    List<String> conflictColumns = const [],
  ]);
  PostgresQueryBuilder onConflictDoUpdate(
    List<String> conflictColumns,
    List<SetRef> updates,
  );
  PostgresQueryBuilder onConflictDoUpdateRaw(
    List<String> conflictColumns,
    String raw,
  );
  PostgresQueryBuilder clearUpsert();
  PostgresQueryBuilder forUpdate();
  PostgresQueryBuilder forUpdateNowait();
  PostgresQueryBuilder forUpdateSkipLocked();
  PostgresQueryBuilder forShare();
  PostgresQueryBuilder forShareNowait();
  PostgresQueryBuilder forShareSkipLocked();
  PostgresQueryBuilder clearRowLock();
  PostgresQueryBuilder hintRaw(String rawHint);
  PostgresQueryBuilder clearHints();
  PostgresQueryBuilder callProcedure(String name);
  PostgresQueryBuilder callProcedureWithOwner(String owner, String name);
  PostgresQueryBuilder callFunction(
    String name, [
    CallReturnIntent returnIntent = CallReturnIntent.scalar,
  ]);
  PostgresQueryBuilder callFunctionWithOwner(
    String owner,
    String name, [
    CallReturnIntent returnIntent = CallReturnIntent.scalar,
  ]);
  PostgresQueryBuilder procParam(Object? value);
  PostgresQueryBuilder procParams(List<Object?> values);
  PostgresQueryBuilder procParamNamed(String name, Object? value);
  PostgresQueryBuilder procParamRaw(String raw);
  PostgresQueryBuilder procParamOut(String name, [String? sqlType]);
  PostgresQueryBuilder procParamInOut(
    String name,
    Object? value, [
    String? sqlType,
  ]);
  PostgresQueryBuilder clearCall();
  PostgresQueryBuilder joinCrossLateral(
    String alias,
    void Function(PostgresQueryBuilder builder) builder, [
    void Function(JoinOnBuilder builder)? on,
  ]);
  PostgresQueryBuilder joinLeftLateral(
    String alias,
    void Function(PostgresQueryBuilder builder) builder, [
    void Function(JoinOnBuilder builder)? on,
  ]);
}

/// The SqliteQueryBuilder view over the single QueryBuilder runtime class.
abstract interface class SqliteQueryBuilder implements SqlBuilderView {
  SqliteQueryBuilder and();
  SqliteQueryBuilder or();
  SqliteQueryBuilder distinct();
  SqliteQueryBuilder clearAll();
  SqliteQueryBuilder clearFrom();
  SqliteQueryBuilder clearGroupBy();
  SqliteQueryBuilder clearHaving();
  SqliteQueryBuilder clearJoin();
  SqliteQueryBuilder clearLimit();
  SqliteQueryBuilder clearOffset();
  SqliteQueryBuilder clearOrderBy();
  SqliteQueryBuilder clearSelect();
  SqliteQueryBuilder clearDistinct();
  SqliteQueryBuilder clearWhere();
  SqliteQueryBuilder clearCte();
  SqliteQueryBuilder clearUnion();
  SqliteQueryBuilder clearInsert();
  SqliteQueryBuilder clearUpdate();
  SqliteQueryBuilder clearDelete();
  SqliteQueryBuilder selectAll();
  SqliteQueryBuilder selectColumn(String table, String column, {String? alias});
  SqliteQueryBuilder selectColumns(List<ColumnRef> columns);
  SqliteQueryBuilder selectRaw(String rawSelect);
  SqliteQueryBuilder selectRaws(List<String> rawSelects);
  SqliteQueryBuilder selectWithBuilder(
    String alias,
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder selectWindow(
    String fn,
    void Function(WindowBuilder builder) over, {
    String? alias,
  });
  SqliteQueryBuilder selectJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode, {
    String? alias,
  });
  SqliteQueryBuilder selectAggregate(
    AggregateFunction aggregate,
    String table,
    String column, {
    String? alias,
    bool distinct = false,
  });
  SqliteQueryBuilder fromTable(String table, {String? alias, String? owner});
  SqliteQueryBuilder fromTables(List<TableRef> tables);
  SqliteQueryBuilder fromRaw(String rawFrom);
  SqliteQueryBuilder fromRaws(List<String> rawFroms);
  SqliteQueryBuilder fromWithBuilder(
    String alias,
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder fromTableFunction(
    String functionName,
    String alias, [
    List<Object?> params = const [],
  ]);
  SqliteQueryBuilder fromTableFunctionWithOwner(
    String owner,
    String functionName,
    String alias, [
    List<Object?> params = const [],
  ]);
  SqliteQueryBuilder fromFunctionRaw(String rawFrom, String alias);
  SqliteQueryBuilder joinTable(
    JoinType joinType,
    String table,
    void Function(JoinOnBuilder builder) on, {
    String? alias,
    String? owner,
  });
  SqliteQueryBuilder joinTables(List<JoinRef> joins);
  SqliteQueryBuilder joinWithBuilder(
    JoinType joinType,
    String alias,
    void Function(SqliteQueryBuilder builder) builder,
    void Function(JoinOnBuilder builder) on,
  );
  SqliteQueryBuilder joinRaw(String rawJoin);
  SqliteQueryBuilder joinRaws(List<String> rawJoins);
  SqliteQueryBuilder where(
    String table,
    String column,
    WhereOperator operator,
    Object? value,
  );
  SqliteQueryBuilder whereBetween(
    String table,
    String column,
    Object? from,
    Object? to,
  );
  SqliteQueryBuilder whereRowValue(
    List<GroupByRef> columns,
    WhereOperator operator,
    List<Object?> values,
  );
  SqliteQueryBuilder whereRowValueIn(
    List<GroupByRef> columns,
    List<List<Object?>> tuples,
  );
  SqliteQueryBuilder whereInValues(
    String table,
    String column,
    List<Object?> values,
  );
  SqliteQueryBuilder whereNotInValues(
    String table,
    String column,
    List<Object?> values,
  );
  SqliteQueryBuilder whereNull(String table, String column);
  SqliteQueryBuilder whereNotNull(String table, String column);
  SqliteQueryBuilder whereRaw(String rawWhere);
  SqliteQueryBuilder whereRaws(List<String> rawWheres);
  SqliteQueryBuilder whereJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode,
    WhereOperator operator,
    Object? value,
  );
  SqliteQueryBuilder whereMatch(
    List<MatchColumnRef> columns,
    String query, [
    FullTextMode mode = FullTextMode.natural,
  ]);
  SqliteQueryBuilder whereMatchRaw(String rawWhere);
  SqliteQueryBuilder whereGroup(
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder whereInWithBuilder(
    String table,
    String column,
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder whereNotInWithBuilder(
    String table,
    String column,
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder whereExistsWithBuilder(
    String table,
    String column,
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder whereNotExistsWithBuilder(
    String table,
    String column,
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder whereExists(
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder whereNotExists(
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder groupByColumn(String table, String column);
  SqliteQueryBuilder groupByColumns(List<GroupByRef> columns);
  SqliteQueryBuilder groupByRaw(String rawGroupBy);
  SqliteQueryBuilder groupByRaws(List<String> rawGroupBys);
  SqliteQueryBuilder having(
    String table,
    String column,
    WhereOperator operator,
    Object? value,
  );
  SqliteQueryBuilder havingAggregate(
    AggregateFunction aggregate,
    String table,
    String column,
    WhereOperator operator,
    Object? value, {
    bool distinct = false,
  });
  SqliteQueryBuilder havingRaw(String rawHaving);
  SqliteQueryBuilder havingRaws(List<String> rawHavings);
  SqliteQueryBuilder havingJsonExtract(
    String table,
    String column,
    String path,
    JsonExtractMode mode,
    WhereOperator operator,
    Object? value,
  );
  SqliteQueryBuilder havingMatch(
    List<MatchColumnRef> columns,
    String query, [
    FullTextMode mode = FullTextMode.natural,
  ]);
  SqliteQueryBuilder havingBetween(
    String table,
    String column,
    Object? from,
    Object? to,
  );
  SqliteQueryBuilder havingInValues(
    String table,
    String column,
    List<Object?> values,
  );
  SqliteQueryBuilder havingNotInValues(
    String table,
    String column,
    List<Object?> values,
  );
  SqliteQueryBuilder havingNull(String table, String column);
  SqliteQueryBuilder havingNotNull(String table, String column);
  SqliteQueryBuilder havingInWithBuilder(
    String table,
    String column,
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder havingNotInWithBuilder(
    String table,
    String column,
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder havingExists(
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder havingNotExists(
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder havingGroup(
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder orderByColumn(
    String table,
    String column,
    OrderByDirection direction, [
    NullsOrder nulls = NullsOrder.none,
  ]);
  SqliteQueryBuilder orderByColumns(List<OrderByRef> columns);
  SqliteQueryBuilder orderByRaw(String rawOrderBy);
  SqliteQueryBuilder orderByRaws(List<String> rawOrderBys);
  SqliteQueryBuilder limit(int limit);
  SqliteQueryBuilder offset(int offset);
  SqliteQueryBuilder insertInto(String table, {String? owner});
  SqliteQueryBuilder insertColumns(List<String> columns);
  SqliteQueryBuilder insertValues(List<Object?> values);
  SqliteQueryBuilder insertSelect(
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder insertRaw(String raw);
  SqliteQueryBuilder updateTable(String table, {String? alias, String? owner});
  SqliteQueryBuilder set(String column, Object? value);
  SqliteQueryBuilder setColumns(List<SetRef> columns);
  SqliteQueryBuilder setRaw(String raw);
  SqliteQueryBuilder deleteFrom(String table, {String? alias, String? owner});
  SqliteQueryBuilder union(void Function(SqliteQueryBuilder builder) builder);
  SqliteQueryBuilder unionAll(
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder intersect(
    void Function(SqliteQueryBuilder builder) builder,
  );
  SqliteQueryBuilder except(void Function(SqliteQueryBuilder builder) builder);
  SqliteQueryBuilder cte(
    String name,
    void Function(SqliteQueryBuilder builder) builder, [
    List<String> columns = const [],
  ]);
  SqliteQueryBuilder cteRecursive(
    String name,
    void Function(SqliteQueryBuilder builder) builder, [
    List<String> columns = const [],
  ]);
  SqliteQueryBuilder cteRaw(String name, String raw);
  SqliteQueryBuilder returning(List<String> columns);
  SqliteQueryBuilder returningRaw(String raw);
  SqliteQueryBuilder clearReturning();
  SqliteQueryBuilder onConflictDoNothing([
    List<String> conflictColumns = const [],
  ]);
  SqliteQueryBuilder onConflictDoUpdate(
    List<String> conflictColumns,
    List<SetRef> updates,
  );
  SqliteQueryBuilder onConflictDoUpdateRaw(
    List<String> conflictColumns,
    String raw,
  );
  SqliteQueryBuilder clearUpsert();
  SqliteQueryBuilder hintRaw(String rawHint);
  SqliteQueryBuilder clearHints();
}
