import 'dart:convert';
import 'dart:io';

/// Embeds the emission corpus into `test/conformance/corpus_data.dart` as a Dart constant.
///
///     dart run tool/embed_goldens.dart
///
/// The corpus is read from the workspace contract package — there is no fetch, no version pin, and
/// no vendored copy. Those existed only because this port used to live in its own repository and had
/// to pull the contract over HTTP from a git tag. In the monorepo the contract is simply a file, and
/// a contract change plus every port that follows it lands in ONE commit.
///
/// The embed step itself survives, and is not redundant with reading the file: the conformance suite
/// must also run under **dart2js**, which is the only way to catch the number divergence between
/// Flutter web and Flutter mobile, and `dart:io` does not exist on the web. So the VM run reads the
/// contract from disk and the dart2js run reads this generated constant. `tool/verify_embed.dart`
/// keeps the two in sync.
const corpusPath = '../../contract/corpora/emission/corpus.json';

void main() {
  final corpus = File(corpusPath);
  if (!corpus.existsSync()) {
    stderr.writeln(
      'Contract corpus not found at $corpusPath.\n'
      'This tool must be run from the dart/query package root.',
    );
    exit(1);
  }
  final source = corpus.readAsStringSync();

  // Base64, not a raw string literal. The corpus is full of SQL with doubled quotes (`''why?''`),
  // which puts `'''` sequences in the text and terminates a Dart triple-quoted string early. Base64
  // has no such hazard, needs no escaping, and decodes identically on the VM and under dart2js.
  final encoded = base64.encode(utf8.encode(source));

  // Four-space continuation indent, matching what `dart format` produces for adjacent string
  // literals — so the generated file is format-stable and never churns CI's format check. (The
  // `// dart format off` directive is not an option: it needs language version >= 3.8, and this
  // package's SDK floor is lower.)
  final chunks = <String>[];
  for (var i = 0; i < encoded.length; i += 96) {
    chunks.add(
        "    '${encoded.substring(i, (i + 96).clamp(0, encoded.length))}'");
  }

  final out = File('test/conformance/corpus_data.dart');
  out.writeAsStringSync('''
// GENERATED by `dart run tool/embed_goldens.dart` — do not edit.
//
// The golden corpus, embedded so the conformance suite can run under dart2js (where dart:io, and
// therefore reading a file, does not exist). Regenerate after any change to
// contract/corpora/emission/corpus.json.
//
// Base64 because the corpus contains SQL with doubled quotes, which would terminate a Dart raw
// string early.

import 'dart:convert';

/// The golden corpus JSON.
String get corpusJson => utf8.decode(base64.decode(_corpusBase64));

const _corpusBase64 =
${chunks.join('\n')};
''');

  stdout.writeln(
      'Embedded ${source.length} bytes (${encoded.length} base64) from $corpusPath into ${out.path}');
}
