/// Generates the per-engine typed views (`lib/src/builder/query_views.dart`) from the ONE runtime
/// `QueryBuilder` class and the hand-owned policy in `tool/view_manifest.dart`.
///
/// PRESENT-BY-DEFAULT: every public builder method is emitted on EVERY view unless that dialect's
/// `absent` set excludes it — the Dart analog of TypeScript's `Exclude<keyof QueryBuilder, AbsentOnX>`,
/// so a newly added builder method lands on every view automatically and can never silently vanish.
/// For each emitted method the return type is rebound to the view (chaining stays narrow) and every
/// `void Function(QueryBuilder ...)` subquery callback is retyped to the view (nested completion
/// narrows one level down); `JoinOnBuilder`/`WindowBuilder`/`MergeBuilder` callbacks are copied
/// verbatim. Engine-native aliases (`updlock`, `insertIgnore`, …) are emitted only on their home view.
///
/// Usage:
///   dart run tool/gen_views.dart          # regenerate the views file
///   dart run tool/gen_views.dart --check  # fail (exit 1) if the committed file is stale
///
/// Dev-only: `package:analyzer` is a dev dependency and this file never ships.
library;

import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';

import 'view_manifest.dart';

const _builderFile = 'lib/src/builder/query_builder.dart';
const _outFile = 'lib/src/builder/query_views.dart';
const _builderClass = 'QueryBuilder';

/// Stable dialect emission order.
const _dialectOrder = ['mssql', 'mysql', 'postgres', 'sqlite'];

void main(List<String> args) {
  final check = args.contains('--check');

  final source = File(_builderFile).readAsStringSync();
  final unit = parseString(content: source).unit;

  final cls = unit.declarations.whereType<ClassDeclaration>().firstWhere(
        (c) => c.namePart.typeName.lexeme == _builderClass,
        orElse: () =>
            throw StateError('class $_builderClass not found in $_builderFile'),
      );

  // The generator understands methods and getters only. A public field would be silently dropped
  // from every view, so refuse to run if one appears — a loud failure beats a quiet capability hole.
  for (final member in cls.body.members) {
    if (member is FieldDeclaration && !member.isStatic) {
      for (final v in member.fields.variables) {
        if (!v.name.lexeme.startsWith('_')) {
          throw StateError(
            'public field ${v.name.lexeme} on $_builderClass is not supported by gen_views',
          );
        }
      }
    }
  }

  final aliasSurfaceNames = allAliasSurfaceNames();
  final builderMethods =
      <MethodDeclaration>[]; // return QueryBuilder -> per view
  final terminals = <MethodDeclaration>[]; // other returns -> shared base

  for (final m in cls.body.members.whereType<MethodDeclaration>()) {
    if (m.isStatic || m.isOperator) continue;
    final name = m.name.lexeme;
    if (name.startsWith('_')) continue;
    final ret = m.returnType?.toSource();
    if (ret == _builderClass) {
      // An alias delegator (e.g. `updlock`) is itself a QueryBuilder-returning method; it is emitted
      // only on its home view from the manifest, never auto-discovered onto every view.
      if (aliasSurfaceNames.contains(name)) continue;
      builderMethods.add(m);
    } else {
      // A return type that MENTIONS QueryBuilder but is not exactly it (`QueryBuilder?`,
      // `QueryBuilder<T>`, `Future<QueryBuilder>`, a typedef alias) would be silently filed as a
      // terminal — un-narrowed and un-hideable on the shared base. Refuse rather than misclassify.
      if (ret != null && ret.contains(_builderClass)) {
        throw StateError(
          'method "$name" returns "$ret", which mentions $_builderClass but is not exactly it — '
          'gen_views cannot classify it; teach the generator this shape explicitly',
        );
      }
      terminals.add(m);
    }
  }

  final methodsByName = {for (final m in builderMethods) m.name.lexeme: m};

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/gen_views.dart — DO NOT EDIT.')
    ..writeln('//')
    ..writeln(
      '// One `abstract interface class` per dialect, redeclaring only the methods that dialect can',
    )
    ..writeln(
      '// run (present-by-default minus tool/view_manifest.dart\'s absent set), with builder-returning',
    )
    ..writeln(
      '// methods rebound to the view and subquery callbacks narrowed to it. `QueryBuilder implements`',
    )
    ..writeln(
      '// all four. Regenerate with `dart run tool/gen_views.dart`; `--check` fails if this is stale.',
    )
    ..writeln('part of \'query_builder.dart\';')
    ..writeln()
    ..writeln(
      '/// The dialect-agnostic tail shared by every view — the members that do not return the builder,',
    )
    ..writeln('/// so they need no per-dialect narrowing.')
    ..writeln('abstract interface class SqlBuilderView {');
  for (final m in terminals) {
    buf.writeln('  ${_renderTerminal(m)}');
  }
  buf
    ..writeln('}')
    ..writeln();

  for (final dialect in _dialectOrder) {
    final policy = viewManifest[dialect]!;
    final view = viewClassName(dialect);
    final seen = <String>{};

    buf
      ..writeln(
          '/// The $view view over the single QueryBuilder runtime class.')
      ..writeln('abstract interface class $view implements SqlBuilderView {');

    for (final m in builderMethods) {
      final name = m.name.lexeme;
      if (policy.absent.contains(name)) continue;
      if (!seen.add(name)) {
        throw StateError('duplicate method "$name" on $view');
      }
      buf.writeln('  ${_renderBuilderMethod(m, view, name)}');
    }

    policy.aliases.forEach((surface, target) {
      if (!policy.absent.contains(target)) {
        throw StateError(
          '$view alias "$surface" -> "$target": the target must be in $dialect.absent so the '
          'generic name is hidden where the alias is shown',
        );
      }
      final targetDecl = methodsByName[target];
      if (targetDecl == null) {
        throw StateError(
          '$view alias "$surface" -> "$target": no such builder method on $_builderClass',
        );
      }
      if (!seen.add(surface)) {
        throw StateError(
            'duplicate identifier "$surface" on $view (alias collision)');
      }
      buf.writeln('  ${_renderBuilderMethod(targetDecl, view, surface)}');
    });

    buf
      ..writeln('}')
      ..writeln();
  }

  final generated = buf.toString();
  _assertNarrowed(generated);
  final formatted = _dartFormat(generated);

  if (check) {
    final existing =
        File(_outFile).existsSync() ? File(_outFile).readAsStringSync() : '';
    if (existing != formatted) {
      stderr.writeln(
        'gen_views: $_outFile is STALE. Run `dart run tool/gen_views.dart` and commit the result.',
      );
      exit(1);
    }
    stdout.writeln('gen_views: $_outFile is up to date.');
  } else {
    File(_outFile).writeAsStringSync(formatted);
    stdout.writeln('gen_views: wrote $_outFile');
  }
}

/// One builder-returning method as a view declaration: return rebound to [view], name set to [name]
/// (the surface name — same as the method for a normal method, the alias name for an alias), and any
/// `void Function(QueryBuilder ...)` subquery callback retyped to [view]. Foreign-builder callbacks
/// (`JoinOnBuilder`/`WindowBuilder`/`MergeBuilder`) never contain the token `Function(QueryBuilder `
/// so they are copied unchanged, as are all ordinary parameters and their default values.
String _renderBuilderMethod(MethodDeclaration m, String view, String name) {
  final typeParams = m.typeParameters?.toSource() ?? '';
  if (m.isGetter) return '$view get $name;';
  final params = m.parameters?.toSource() ?? '()';
  // Retype subquery callbacks to the view. Match `Function(QueryBuilder` whether the inner param is
  // named (`Function(QueryBuilder builder)`) or not (`Function(QueryBuilder)`) — a trailing-space-only
  // match would silently leave the no-name form wide. `_assertNarrowed` below is the backstop.
  final narrowed = params.replaceAllMapped(
    RegExp('Function\\($_builderClass(?=[ )])'),
    (_) => 'Function($view',
  );
  return '$view $name$typeParams$narrowed;';
}

/// Backstop for the callback-narrowing rewrite: no generated view line may still mention a WIDE
/// `Function(QueryBuilder` — that would be an un-narrowed subquery callback leaking the full surface
/// one level down. Fails loudly rather than emitting a dishonest view. (`Function(JoinOnBuilder`,
/// `Function(MergeBuilder`, `Function(WindowBuilder` are foreign builders and are left untouched.)
void _assertNarrowed(String generated) {
  final leak = RegExp('Function\\($_builderClass[ )]');
  if (leak.hasMatch(generated)) {
    final line = generated
        .split('\n')
        .firstWhere((l) => leak.hasMatch(l), orElse: () => '');
    throw StateError(
      'gen_views: an un-narrowed subquery callback survived on a view: "${line.trim()}". '
      'The narrowing rewrite in _renderBuilderMethod did not match this callback shape.',
    );
  }
}

/// A non-builder-returning member (getter or terminal method) as a shared-base declaration, copied
/// verbatim from the source.
String _renderTerminal(MethodDeclaration m) {
  final ret = m.returnType?.toSource() ?? 'dynamic';
  final name = m.name.lexeme;
  if (m.isGetter) return '$ret get $name;';
  final typeParams = m.typeParameters?.toSource() ?? '';
  final params = m.parameters?.toSource() ?? '()';
  return '$ret $name$typeParams$params;';
}

/// Runs `dart format` on [source] via a temp file so both the write path and `--check` compare
/// byte-identical, format-clean output (the repo gate is `dart format --set-exit-if-changed .`).
String _dartFormat(String source) {
  final tmpDir = Directory.systemTemp.createTempSync('gen_views');
  try {
    final tmp = File('${tmpDir.path}/query_views.dart')
      ..writeAsStringSync(source);
    final result = Process.runSync('dart', ['format', tmp.path]);
    if (result.exitCode != 0) {
      stderr.writeln('gen_views: dart format failed:\n${result.stderr}');
      exit(2);
    }
    return tmp.readAsStringSync();
  } finally {
    tmpDir.deleteSync(recursive: true);
  }
}
